2 homework (9 sprint)
altynchach/playlist2 pull request #2
Opened 2024-06-24 22:11 UTC by altynchach

2024-06-25 21:04 UTC, DmitrijEgorow commented
![Screenshot_20240625_224820](https://github.com/altynchach/playlist2/assets/36837067/0d21ef7d-085c-4602-916e-7f58e097e2aa)

- [ ] Курсор должен быть синего цвета согласно дизайну
- [ ] Подсказка не должна показываться при вводе текста, сейчас она белая
- [ ] Нет стрелки назад слева от заголовка

2024-06-25 21:04 UTC, DmitrijEgorow commented
- [ ] Нет отступа заголовка от края экрана

![Screenshot_20240625_225138](https://github.com/altynchach/playlist2/assets/36837067/098fde69-bb7f-499e-90b9-4415fe876240)

2024-06-25 21:05 UTC, DmitrijEgorow commented
- [ ] Иконки не кликаются
- [ ] Нет отступа заголовка от стрелки

https://github.com/altynchach/playlist2/assets/36837067/c1c5e33e-feba-403a-8bc4-42a42148d61a

2024-06-25 21:14 UTC, DmitrijEgorow requested changes

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_settings.xml
>                      android:id="@+id/ivShareApp"
Здесь почему-то стиль именования camelCase, а выше через _

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_search.xml
> +    </GridLayout>
Почему GridLayout?

2024-06-25 21:14 UTC, DmitrijEgorow commented on .idea/deploymentTargetSelector.xml
Стоит оформить .gitignore

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ActivitySearch.kt
>  class ActivitySearch : AppCompatActivity() {
Классы всегда называются с постфиксом Activity/Service/Fragment/..., не с префиксом
Пример: `AppCompatActivity`

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ActivitySearch.kt
> +            searchText = savedInstanceState.getString("SEARCH_QUERY", "")
Ключ лучше вынести в константу, дабы избежать ошибок в будущем

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ActivitySettings.kt
> +                putExtra(Intent.EXTRA_EMAIL, arrayOf("your_email@example.com"))
string-res

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ActivitySettings.kt
> +            val browserIntent = Intent(Intent.ACTION_VIEW, Uri.parse("https://yandex.ru/legal/practicum_offer/"))
string-res

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/res/values-night/styles.xml
> +        <item name="android:layout_height">match_parent</item>
Вот эти два атрибуты я бы не выносил в стиль, а вот все остальные уже скорее по смыслу относятся именно к стилю элемента

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/res/values/colors.xml
>      <color name="blue_switch2">#9FBBF3</color>
Плохие названия

2024-06-25 21:14 UTC, DmitrijEgorow commented on app/src/main/res/values/styles.xml
> +    <style name="header_page">
Стоит унифицировать названия стилей

2024-06-26 19:23 UTC, altynchach commented on app/src/main/res/layout/activity_settings.xml
>                      android:id="@+id/ivShareApp"
Когда делала, не перестроилась с кэмела после работы. Исправила

2024-06-26 21:43 UTC, altynchach commented on app/src/main/res/layout/activity_search.xml
> +    </GridLayout>
Хотела попробовать верстать по сетке.

2024-07-03 15:17 UTC, merged